# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - security_scan
  - publish
  - deploy
 

variables:
  DOTNET_VERSION: "9.0"
  SOLUTION_FILE: "AdvertisingPlatforms.sln"
  PROJECT_PATH: "AdvertisingPlatforms/AdvertisingPlatforms.Web.csproj"
  BUILD_CONFIGURATION: "Release"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  ARTIFACTS_DIR: "$CI_PROJECT_DIR/artifacts"
  CONNECTION_STRING: "Server=88.218.62.221;Database=delivery4;User Id=user4;Password=P@ssw0rd_4;"
  DOCKER_REGISTRY: "em-gitlab.ru:5050"
  DOCKER_REGISTRY_PASSWORD: "GvnlTfqaYe/zhdu83fLVHXveP2k0jCrIJBCZXK2bm8w="
  DOCKER_IMAGE: "em-gitlab.ru/em_dotnet_e5/advertisingplatformsanna"
  DOCKER_TAG: "$CI_COMMIT_REF_SLUG"
  TRIVY_CACHE_DIR: "$CI_PROJECT_DIR/.trivycache"
  NUGET_PACKAGES_DIR: "$CI_PROJECT_DIR/.nuget/packages"

  USER_PORT: 5004
  SERVER_USER: root
  SERVER_IP: 88.218.62.221
  TEST: test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .nuget/

build-job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore --output ./publish/
  artifacts:
    paths:
      - "**/bin/Release/**"
      - "**/publish/**"
    expire_in: 1 week
  only:
    - modul_3

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
     - dotnet test
  when: manual

trivy-scan-job:
  stage: security_scan
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  dependencies:
    - build-job
  script:
    - trivy fs --security-checks vuln --severity HIGH,CRITICAL --format json -o trivy-report.json ./publish/
    - trivy fs --security-checks vuln --severity HIGH,CRITICAL --format table ./publish/
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 week
  allow_failure: false  # Если найдутся уязвимости - пайплайн упадёт

publish-job:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet publish --configuration Release --output ./publish
  artifacts:
    paths:
      - ./publish/
    expire_in: 1 week
  only:
    - modul_3

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
