// <auto-generated />
using System;
using AdvertisingPlatforms.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvertisingPlatforms.DAL.Migrations
{
    [DbContext(typeof(AdvertisingPlatformsDbContext))]
    [Migration("20250612112450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.AdvertisementDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.AdvertisingPlatformDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("LocationId");

                    b.ToTable("AdvertisingPlatforms");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.LocationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.AdvertisingPlatformDb", b =>
                {
                    b.HasOne("AdvertisingPlatforms.DAL.Entities.AdvertisementDb", "Advertisement")
                        .WithMany("AdvertisingPlatforms")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdvertisingPlatforms.DAL.Entities.LocationDb", "Location")
                        .WithMany("AdvertisingPlatforms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.LocationDb", b =>
                {
                    b.HasOne("AdvertisingPlatforms.DAL.Entities.LocationDb", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.AdvertisementDb", b =>
                {
                    b.Navigation("AdvertisingPlatforms");
                });

            modelBuilder.Entity("AdvertisingPlatforms.DAL.Entities.LocationDb", b =>
                {
                    b.Navigation("AdvertisingPlatforms");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
